title: 'strbck.github.io'
description: "Carter Richard's personal Github pages website."
baseurl:
url: "https://strbck.github.io"

header_pages:
  - index.md
  - about.md
  - projects.md
  - apps.md
  - meet.md

style: dark

footer: 'Connect with me on <a href="https://www.linkedin.com/in/carterkrichard/">LinkedIn</a>.'

# Build settings
markdown: kramdown
remote_theme:  b2a3e8/jekyll-theme-console

google_analytics: G-WLW268MS29

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
